scalar Time

type Query {
  currentUser: User!
}

type Mutation {
  createGroup(input: GroupInput!): Group!
  createGroupMember(groupId: ID!, input: GroupMemberInput!): GroupMember!
  createTransaction(groupId: ID!, input: TransactionInput!): Transaction!
}

type User {
  id: Int!
  groups: [Group!]!
  group(id: ID!): Group!
}

type Group {
  id: Int!
  name: String!
  members: [GroupMember!]!
  transactions: [Transaction!]!
  settlements: [Settlement!]!
}

type GroupMember {
  id: Int!
  name: String
  role: GroupMemberRole!
}

type Transaction {
  id: Int!
  amount: Float!
  description: String
  createdAt: Time!
  splits: [TransactionSplit!]!
  member: GroupMember!
}

type TransactionSplit {
  transactionId: Int!
  memberId: Int!
  amount: Float!
  member: GroupMember!
}

type Settlement {
  from: GroupMember!
  to: GroupMember!
  amount: Float!
}

input GroupInput {
  name: String
}

input GroupMemberInput {
  name: String
}

input TransactionInput {
  amount: Float!
  description: String
  memberId: Int!
  splits: [TransactionSplitInput!]!
}

input TransactionSplitInput {
  amount: Float!
  memberId: Int!
}

enum GroupMemberRole {
  owner
  member
}